version: '3.9'

services: 
  datadb: 
    container_name: datadb
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - 15432:5432  
    volumes:
      - pgdata:/var/lib/postgresql/data

  django-app:
    container_name: django-app
    build: .
    image: app:latest
    env_file:
      - .env
    volumes:
      - ./str:/app
    ports:
      - 8001:8000
    depends_on:
      - datadb
    entrypoint: /django.sh
    command: >
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "


  fast-api:
    build: ./str/api   # sizning ikkinchi fastapi loyihangiz katalogi
    container_name: fast-api
    env_file:
      - .env
    depends_on:
      - datadb
    volumes:
      - ./str/api:/app   # src fayllarni synhron qiladi
    ports:
      - "9999:9000"
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
  
      
volumes:
  pgdata:



# fastapi-app:
  #   build: ./str/api
  #   container_name: fastapi-app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - datadb
  #   ports:
  #     - "8002:8000"
  #   volumes:
  #     - ./str/api:/app   # shuni qo'shing
