version: '3.9'

services: 
  datadb: 
    container_name: datadb
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - 15432:5432  
    volumes:
      - pgdata:/var/lib/postgresql/data

  django-app:
    container_name: django-app
    build: .
    image: app:latest
    env_file:
      - .env
    volumes:
      - ./str:/app
    ports:
      - 8001:8000
    depends_on:
      - datadb
    entrypoint: /django.sh
    command: >
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

volumes:
  pgdata:


